#!/usr/bin/env python3
"""
Wave 3: address remaining NGSL gap lemmas (dubious metaphors OK).

1. Collapse near-duplicates / -ly / synonyms → ngsl-lemma-map kind=redundant
2. Soft-match remaining gaps onto empty published rows (token / prefer table)
3. Auto-assign leftover gaps to leftover empty rows (any mnemonic stretch)
4. Force-redundant any overflow gaps
5. Rebuild ngsl-metaphor-extra.csv from final singles

Run:
  python3 scripts/wave3-gap-fill.py
  npm run ngsl-coverage
"""
from __future__ import annotations

import csv
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PUBLISHED = ROOT / "data" / "lexicon-published.csv"
COVERAGE = ROOT / "data" / "ngsl-coverage.csv"
LEMMA_MAP = ROOT / "data" / "ngsl-lemma-map.csv"
EXTRA = ROOT / "data" / "ngsl-metaphor-extra.csv"

# Prefer these empty (or any) published literals when soft-matching.
PREFER: dict[str, str] = {
    "price": "money-bag",
    "answer": "speech",
    "debate": "speaking-head",
    "order": "clipboard",
    "form": "page",
    "clear": "bright",
    "particular": "pushpin",
    "specific": "pushpin",
    "exist": "sparkles",
    "apply": "memo",
    "board": "black-square",
    "invest": "chart-up",
    "task": "ballot-box",
    "earn": "dollar",
    "survey": "bar-chart",
    "duty": "medal",
    "obvious": "eyes",
    "bind": "chains",
    "belong": "key",
    "fashion": "dress",
    "army": "helmet",
    "council": "classical-building",
    "editor": "pen",
    "sight": "eye",
    "generate": "lightning",
    "delivery": "package",
    "quote": "speech",
    "violence": "boom",
    "minister": "necktie",
    "noise": "speaker-high",
    "manner": "bow",
    "occasion": "confetti-ball",
    "familiar": "wave",
    "ignore": "see-no-evil",
    "destroy": "boom",
    "affair": "ring",
    "civil": "classical-building",
    "locate": "pushpin",
    "citizen": "silhouette",
    "domestic": "house",
    "load": "package",
    "troop": "guard",
    "remind": "bell",
    "arrangement": "bouquet",
    "prison": "brick",
    "switch": "plug",
    "acquire": "shopping-bag",
    "corporate": "office",
    "tough": "bicep",
    "representative": "silhouette",
    "capacity": "battery",
    "shake": "handshake",
    "shoe": "mans-shoe",
    "ad": "megaphone",
    "fee": "receipt",
    "hall": "stadium",
    "regulation": "prohibited",
    "escape": "running",
    "relax": "beach",
    "tourist": "camera",
    "afford": "credit-card",
    "suspect": "detective",
    "cup": "tea",
    "description": "memo",
    "confidence": "bicep",
    "industrial": "factory",
    "complain": "rage",
    "perspective": "telescope",
    "error": "cross",
    "assess": "abacus",
    "register": "clipboard",
    "asset": "gemstone",
    "relevant": "pushpin",
    "frame": "framed-picture",
    "hire": "briefcase",
    "internal": "gear",
    "chain": "link",
    "literature": "book",
    "victim": "bandage",
    "threaten": "warning",
    "division": "divide",
    "secure": "locked",
    "amaze": "mind-blown",
    "device": "phone",
    "channel": "television",
    "investigate": "magnify",
    "rank": "medal",
    "typical": "clipboard",
    "friendly": "smile",
    "resident": "house",
    "provision": "package",
    "concentrate": "brain",
    "export": "ship",
    "consist": "puzzle-piece",
    "graduate": "graduation-cap",
    "brand": "label",
    "moral": "scale",
    "insist": "fist",
    "combination": "puzzle-piece",
    "abuse": "broken-heart",
    "session": "calendar",
    "wed": "wedding",
    "atmosphere": "foggy",
    "rely": "handshake",
    "identity": "name-tag",
    "permit": "ticket",
    "lovely": "rose",
    "youth": "child",
    "journey": "compass",
    "stretch": "person",
    "declare": "megaphone",
    "retire": "beach",
    "tiny": "ant",
    "careful": "warning",
    "suitable": "check",
    "native": "house",
    "terrible": "skull",
    "ordinary": "white",
    "selection": "check",
    "mental": "brain",
    "participant": "handshake",
    "vision": "eye",
    "personality": "theater",
    "fat": "hamburger",
    "fellow": "silhouette",
    "chemical": "test-tube",
    "capture": "camera",
    "tip": "lightbulb",
    "discount": "label",
    "chairman": "judge",
    "proportion": "scale",
    "disappear": "ghost",
    "shout": "megaphone",
    "yard": "house",
    "constant": "infinity",
    "hill": "mountain",
    "considerable": "mountain",
    "instruction": "book",
    "intelligence": "brain",
    "ideal": "star",
    "folk": "silhouettes",
    "presentation": "clipboard",
    "joint": "handshake",
    "compete": "trophy",
    "poll": "ballot-box",
    "reduction": "minus",
    "reserve": "bank",
    "bore": "yawn",
    "mission": "rocket",
    "tone": "music-note",
    "neighborhood": "house",
    "justice": "scale",
    "phase": "crescent-moon",
    "rush": "running",
    "formal": "necktie",
    "employer": "briefcase",
    "latter": "checkered-flag",
    "ban": "no-entry",
    "steal": "ninja",
    "protest": "fist",
    "index": "point",
    "circle": "red",
    "helpful": "raise-hands",
    "command": "crown",
    "attractive": "sparkles",
    "unable": "prohibited",
    "joke": "clown",
    "column": "classical-building",
    "electronic": "laptop",
    "impose": "hammer",
    "criminal": "police",
    "ancient": "hourglass-done",
    "coast": "beach",
    "ill": "sick",
    "multiple": "asterisk",
    "yield": "rice-plant",
    "legislation": "scroll",
    "county": "world-map",
    "unlike": "shuffle",
    "assistant": "handshake",
    "implement": "wrench",
    "chart": "bar-chart",
    "advise": "speech",
    "acknowledge": "bow",
    "reward": "trophy",
    "hat": "top-hat",
    "academic": "graduation-cap",
    "voter": "ballot-box",
    "meanwhile": "hourglass",
    "accuse": "point",
    "scientific": "microscope",
    "wage": "dollar",
    "absence": "empty-nest",
    "remark": "speech",
    "rare": "gemstone",
    "intention": "thought",
    "settlement": "handshake",
    "gap": "hole",
    "minimum": "minus",
    "northern": "snowflake",
    "estate": "house",
    "expose": "flashlight",
    "shut": "door",
    "resolve": "check",
    "critic": "thumbs-down",
    "variable": "chart-up",
    "enormous": "elephant",
    "permanent": "infinity",
    "pursue": "running",
    "urge": "point",
    "appoint": "crown",
    "talent": "star",
    "prior": "back",
    "priority": "pushpin",
    "phrase": "speech",
    "stable": "anchor",
    "mere": "dash",
    "resolution": "check",
    "communicate": "speech",
    "exhibition": "framed-picture",
    "producer": "clapperboard",
    "regional": "world-map",
    "immediate": "lightning",
    "incident": "boom",
    "childhood": "child",
    "slip": "banana",
    "accompany": "holding-hands",
    "politician": "classical-building",
    "knock": "door",
    "salary": "dollar",
    "illustrate": "crayon",
    "imply": "thought",
    "breakfast": "cooking",
    "temporary": "hourglass",
    "liberal": "dove",
    "qualify": "check",
    "competitive": "trophy",
    "habit": "repeat",
    "core": "apple",
    "emotional": "heart",
    "aircraft": "airplane",
    "self": "mirror",
    "existence": "sparkles",
    "panel": "window",
    "prime": "1",
    "appointment": "calendar",
    "emphasize": "exclamation-red",
    "maximum": "plus",
    "bother": "mosquito",
    "initiative": "rocket",
    "sharp": "knife",
    "diet": "salad",
    "motion": "dancing",
    "gray": "cloud",
    "complicate": "knot",
    "discipline": "martial-arts",
    "disappoint": "disappointed",
    "assumption": "thought",
    "freeze": "snowflake",
    "extreme": "volcano",
    "passage": "bridge-night",
    "reputation": "star",
    "forth": "forward",
    "negotiation": "handshake",
    "democracy": "ballot-box",
    "pocket": "jeans",
    "lucky": "four-leaf-clover",
    "observation": "eye",
    "concentration": "brain",
    "implication": "thought",
    "deserve": "trophy",
    "unusual": "alien",
    "classic": "classical-building",
    "interaction": "handshake",
    "repair": "wrench",
    "collapse": "construction",
    "borrow": "handshake",
    "fundamental": "rock",
    "abroad": "airplane",
    "capable": "bicep",
    "defeat": "skull",
    "presidential": "classical-building",
    "perfectly": "hundred",
    "enhance": "sparkles",
    "educational": "graduation-cap",
    "distinguish": "eyes",
    "substantial": "mountain",
    "nearby": "pushpin",
    "manufacturer": "factory",
    "slide": "playground",
    "valuable": "gemstone",
    "breast": "breastfeeding",
    "cope": "bicep",
    "accommodation": "hotel",
    "highlight": "flashlight",
    "reporter": "microphone",
    "climate": "thermometer",
    "shirt": "t-shirt",
    "exception": "asterisk",
    "chip": "fries",
    "winner": "trophy",
    "encounter": "handshake",
    "excuse": "bow",
    "partly": "pie",
    "urban": "cityscape",
    "confuse": "confused",
    "southern": "sun",
    "output": "printer",
    "beauty": "rose",
    "massive": "elephant",
    "install": "hammer",
    "mathematics": "abacus",
    "upper": "up",
    "creation": "artist",
    "occupy": "seat",
    "outline": "pencil",
    "sufficient": "check",
    "preserve": "jar",
    "swing": "golf",
    "illness": "sick",
    "journalist": "microphone",
    "advertisement": "megaphone",
    "consistent": "repeat",
    "aside": "left",
    "comfort": "couch-lamp",
    "severe": "warning",
    "prospect": "crystal-ball",
    "plot": "crystal-ball",
    "neck": "scarf",
    "criteria": "clipboard",
    "integrate": "puzzle-piece",
    "criticism": "thumbs-down",
    "convention": "classical-building",
    "bet": "slot-machine",
    "retain": "floppy-disk",
    "sequence": "numbers",
    "plain": "white",
    "rural": "farmer",
    "abandon": "wastebasket",
    "examination": "magnify",
    "efficient": "lightning",
    "revolution": "cyclone",
    "delight": "grin",
    "spell": "letters",
    "premise": "brick",
    "lean": "person",
    "dramatic": "theater",
    "differ": "shuffle",
    "grateful": "pray",
    "protein": "meat",
    "distribute": "package",
    "intellectual": "nerd",
    "derive": "seedling",
    "crucial": "exclamation-red",
    "unemployment": "briefcase",
    "crop": "rice-plant",
    "minority": "silhouettes",
    "origin": "seedling",
    "interpretation": "crystal-ball",
    "gentleman": "man",
    "drama": "theater",
    "landscape": "national-park",
    "educate": "graduation-cap",
    "toy": "teddy-bear",
    "fault": "cross",
    "minor": "baby",
    "hunt": "bow",
    "negotiate": "handshake",
    "dominate": "crown",
    "supplier": "package",
    "peer": "silhouette",
    "pension": "older-person",
    "acquisition": "shopping-bag",
    "laughter": "laugh",
    "recognition": "medal",
    "assistance": "raise-hands",
    "roof": "house",
    "retirement": "beach",
    "variation": "shuffle",
    "proof": "check",
    "soil": "seedling",
    "smart": "nerd",
    "layer": "onion",
    "upset": "cry",
    "representation": "silhouette",
    "preparation": "clipboard",
    "dispute": "sword-crossed",
    "edition": "book",
    "entertainment": "circus",
    "honest": "handshake",
    "undertake": "bicep",
    "retail": "cart",
    "wire": "plug",
    "unlikely": "think",
    "gay": "rainbow",
    "publication": "newspaper",
    "slight": "dash",
    "unknown": "question-red",
    "framework": "brick",
    "zone": "no-entry",
    "restrict": "prohibited",
    "trace": "footprints",
    "inch": "ruler",
    "equivalent": "equals",
    "solid": "brick",
    "enterprise": "office",
    "governor": "classical-building",
    "uniform": "guard",
    "pitch": "baseball",
    "contemporary": "watch",
    "gate": "door",
    "ease": "relief",
    "specialist": "microscope",
    "assure": "handshake",
    "profile": "silhouette",
    "mood": "thermometer",
    "episode": "clapperboard",
    "crack": "broken-heart",
    "symptom": "thermometer",
    "era": "hourglass-done",
    "coverage": "umbrella",
    "tension": "stressed",
    "sensitive": "flower",
    "input": "keyboard",
    "isolate": "island",
    "prisoner": "chains",
    "eliminate": "wastebasket",
    "tight": "knot",
    "secondary": "2",
    "welfare": "heart",
    "recruit": "raise-hands",
    "exclude": "prohibited",
    "string": "yarn",
    "persuade": "speech",
    "inspire": "sparkles",
    "grand": "castle",
    "hence": "right",
    "crew": "silhouettes",
    "phenomenon": "comet",
    "restore": "recycling",
    "formula": "test-tube",
    "perceive": "eye",
    "routine": "calendar",
    "sink": "bathtub",
    "anymore": "stopwatch",
    "supporter": "raise-hands",
    "steady": "anchor",
    "meter": "ruler",
    "sail": "boat",
    "disaster": "volcano",
    "pace": "running",
    "devote": "heart",
    "terrorist": "bomb",
    "justify": "scale",
    "vital": "heart",
    "external": "globe",
    "obligation": "chains",
    "sir": "man",
    "evaluate": "abacus",
    "pub": "beer",
    "territory": "world-map",
    "boundary": "passport-control",
    "restriction": "prohibited",
    "foundation": "brick",
    "tune": "music-note",
    "bid": "raise-hand",
    "breed": "dog",
    "extraordinary": "sparkles",
    "brilliant": "star",
    "adviser": "owl",
    "stem": "herb",
    "reverse": "reload",
    "mode": "gear",
    "awful": "skull",
    "pose": "person",
    "adjust": "wrench",
    "creative": "artist",
    "nowadays": "watch",
    "poem": "scroll",
    "agricultural": "farmer",
    "competitor": "trophy",
    "alcohol": "wine",
    "festival": "circus",
    "van": "bus",
    "confident": "bicep",
    "curve": "curling",
    "knee": "leg",
    "overcome": "mountain",
    "depth": "ocean-wave",
    "entrance": "door",
    "log": "wood",
    "giant": "elephant",
    "substance": "test-tube",
    "extensive": "globe",
    "interpret": "crystal-ball",
    "independence": "fireworks",
    "inner": "heart",
    "harm": "warning",
    "consult": "speech",
    "pink": "rose",
    "shadow": "crescent-moon",
    "strip": "scissors",
    "smooth": "soap",
    "intervention": "raise-hands",
    "impress": "star",
    "vice": "ogre",
    "radical": "volcano",
    "behave": "person",
    "dimension": "ruler",
    "infection": "microbe",
    "jacket": "coat",
    "efficiency": "lightning",
    "statistic": "bar-chart",
    "resort": "beach",
    "broadcast": "radio",
    "membership": "ticket",
    "blind": "see-no-evil",
    "pure": "droplet",
    "bloody": "blood-drop",
    "ally": "handshake",
    "bend": "curling",
    "mature": "older-person",
    "disturb": "bell",
    "sustain": "seedling",
    "flood": "ocean-wave",
    "poverty": "broken-heart",
    "crazy": "zany",
    "cite": "speech",
    "parallel": "train",
    "gender": "transgender",
    "sponsor": "handshake",
    "accurate": "bullseye",
    "dealer": "cart",
    "button": "radio",
    "burden": "package",
    "shareholder": "chart-up",
    "bowl": "cereal",
    "discovery": "telescope",
    "resistance": "shield",
    "frequency": "radio",
    "criticize": "thumbs-down",
    "tap": "point",
    "philosophy": "owl",
    "attribute": "label",
    "approval": "ok",
    "entitle": "ticket",
    "lend": "handshake",
    "involvement": "handshake",
    "exposure": "camera",
    "conventional": "classical-building",
    "digital": "laptop",
    "translate": "globe",
    "edit": "pen",
    "formation": "brick",
    "deposit": "bank",
    "pleasant": "smile",
    "overseas": "airplane",
    "advocate": "megaphone",
    "establishment": "classical-building",
    "summary": "clipboard",
    "rough": "rock",
    "recovery": "green",
    "characterize": "label",
    "specify": "pushpin",
    "exact": "bullseye",
    "spin": "cyclone",
    "operator": "gear",
    "dig": "pick",
    "drag": "person",
    "mount": "mountain",
    "wrap": "wrapped-gift",
    "anticipate": "crystal-ball",
    "dependent": "link",
    "specialize": "microscope",
    "angle": "ruler",
    "precise": "ruler",
    "rival": "sword-crossed",
    "offense": "police",
    "teenager": "child",
    "admire": "star",
    "moderate": "scale",
    "surgery": "hospital",
    "musician": "microphone",
    "significance": "star",
    "illegal": "prohibited",
    "charity": "heart",
    "universal": "globe",
    "constitute": "brick",
    "adequate": "check",
    "consultant": "briefcase",
    "historian": "scroll",
    "cousin": "family",
    "visual": "eye",
    "keen": "eyes",
    "ethnic": "globe",
    "twin": "silhouettes",
    "clinical": "hospital",
    "eastern": "sunrise",
    "adapt": "lizard",
    "sand": "beach",
    "cap": "billed-cap",
    "prompt": "lightning",
    "charm": "sparkles",
    "react": "boom",
    "lecture": "graduation-cap",
    "venture": "rocket",
    "compound": "test-tube",
    "mess": "poop",
    "preference": "star",
    "comprehensive": "globe",
    "incentive": "carrot",
    "league": "trophy",
    "dialog": "speech",
    "dismiss": "wave",
    "margin": "page",
    "beneath": "down",
    "opponent": "sword-crossed",
    "resist": "shield",
    "capability": "bicep",
    "absolute": "hundred",
    "correspond": "email",
    "stroke": "swimming",
    "dare": "lion",
    "barrier": "construction",
    "rid": "wastebasket",
    "divorce": "broken-heart",
    "ruin": "house",
    "bury": "headstone",
    "counsel": "speech",
    "tendency": "chart-up",
    "frequent": "repeat",
    "motor": "motorcycle",
    "survival": "life-ring",
    "counter": "abacus",
    "possess": "key",
    "permission": "ticket",
    "valley": "mountain",
    "mad": "rage",
    "visible": "eye",
    "electric": "lightning",
    "impressive": "star",
    "evolution": "dna",
    "violent": "boom",
    "slave": "chains",
    "wealthy": "money-bag",
    "architecture": "classical-building",
    "acceptable": "ok",
    "coal": "rock",
    "measurement": "ruler",
    "random": "game-die",
    "depress": "cry",
    "illustration": "crayon",
    "burst": "boom",
    "privilege": "crown",
    "buyer": "cart",
    "mutual": "handshake",
    "rail": "train",
    "motivate": "rocket",
    "laboratory": "test-tube",
    "mortgage": "house",
    "promotion": "chart-up",
    "fulfill": "check",
    "dust": "broom",
    "dedicate": "heart",
    "skirt": "dress",
    "province": "world-map",
    "march": "medal",
    "evaluation": "abacus",
    "compromise": "handshake",
    "weakness": "low-battery",
    "announcement": "megaphone",
    "opera": "theater",
    "contest": "trophy",
    "brush": "paintbrush",
    "embarrass": "blush",
    "gallery": "framed-picture",
    "aggressive": "rage",
    "format": "page",
    "literary": "book",
    "embrace": "hug",
    "publisher": "newspaper",
    "celebration": "party",
    "compensation": "dollar",
    "weigh": "scale",
    "deficit": "chart-down",
    "flash": "lightning",
    "equation": "abacus",
    "gesture": "wave",
    "entertain": "circus",
    "fantastic": "sparkles",
    "assign": "clipboard",
    "inflation": "chart-up",
    "historic": "classical-building",
    "injure": "injured",
    "remote": "satellite",
    "therapy": "pill",
    "twist": "pretzel",
    "personnel": "silhouettes",
    "imagination": "thought",
    "disagree": "cross",
    "throat": "microphone",
    "insight": "lightbulb",
    "tackle": "football",
    "exceed": "chart-up",
    "expenditure": "money-bag",
    "joy": "grin",
    "reliable": "anchor",
    "poet": "scroll",
    "ceremony": "wedding",
    "pile": "book",
    "mixture": "cocktail",
    "scholar": "graduation-cap",
    "psychological": "brain",
    "stake": "game-die",
    "creature": "dragon",
    "partnership": "handshake",
    "participation": "handshake",
    "clause": "scroll",
    "penalty": "prohibited",
    "chamber": "door",
    "fancy": "sparkles",
    "poetry": "scroll",
    "clothing": "t-shirt",
    "shelf": "book",
    "boost": "rocket",
    "tail": "lizard",
    "possession": "key",
    "abortion": "pregnant",
    "curious": "think",
    "wooden": "wood",
    "tale": "book",
    "democratic": "ballot-box",
    "maintenance": "wrench",
    "pot": "cooking",
    "strengthen": "bicep",
    "constraint": "chains",
    "fold": "pray",
    "undergo": "hourglass",
    "scope": "telescope",
    "pretend": "theater",
    "diversity": "rainbow",
    "allege": "speech",
    "pride": "rainbow",
    "intense": "fire",
    "inquiry": "magnify",
    "resign": "wave",
    "strict": "prohibited",
    "concrete": "brick",
    "damn": "cursing",
    "distinct": "star",
    "humor": "clown",
    "limitation": "prohibited",
    "indication": "point",
    "stability": "anchor",
    "wise": "owl",
    "neglect": "wastebasket",
    "jail": "chains",
    "shelter": "house",
    "carbon": "factory",
    "regulate": "gear",
    "trigger": "water-pistol",
    "pipe": "toilet",
    "destruction": "boom",
    "flag": "triangle-flag",
    "mystery": "crystal-ball",
    "whisper": "shush",
    "rear": "back",
    "menu": "page",
    "species": "paw-prints",
    "bless": "pray",
    "airline": "airplane",
    "amendment": "pen",
    "jury": "judge",
    "cooperation": "handshake",
    "civilian": "person",
    "composition": "music-notes",
    "bunch": "grape",
    "racial": "silhouettes",
    "greet": "wave",
    "sanction": "no-entry",
    "trick": "joker",
    "paragraph": "page",
    "maker": "hammer",
    "stimulate": "lightning",
    "belt": "jeans",
    "narrative": "book",
    "tissue": "paper-roll",
    "invent": "lightbulb",
    "tourism": "camera",
    "pro": "thumbs-up",
    "stair": "ladder",
    "hesitate": "think",
    "motivation": "rocket",
    "romantic": "heart",
    "interior": "couch-lamp",
    "stomach": "hamburger",
    "championship": "trophy",
    "servant": "bow",
    "immigrant": "airplane",
    "excess": "plus",
    "complexity": "knot",
    "liability": "chains",
    "extract": "syringe",
    "implementation": "gear",
    "bias": "scale",
    "catalog": "book",
    "continuous": "infinity",
    "golden": "gold",
    "stamp": "postbox",
    "guideline": "clipboard",
    "biological": "dna",
    "consume": "cutlery",
    "luxury": "gemstone",
    "adventure": "compass",
    "fence": "construction",
    "exhaust": "sleep",
    "attraction": "ferris-wheel",
    "veteran": "medal",
    "nerve": "brain",
    "determination": "bicep",
    "fiction": "book",
    "carpet": "prayer-bead",
    "cluster": "grape",
    "confusion": "confused",
    "hurry": "running",
    "logic": "brain",
    "controversial": "speaking-head",
    "raw": "meat",
    "grammar": "letters",
    "hint": "lightbulb",
    "liquid": "droplet",
    "panic": "scream",
    "uncle": "man",
    "slope": "skiing",
    "happiness": "grin",
    "vessel": "ship",
    "verb": "letters",
    "reckon": "think",
    "silly": "clown",
    "transportation": "bus",
    "comedy": "clown",
    "chase": "running",
    "storage": "package",
    "horrible": "skull",
    "sheep": "ewe",
    "lover": "couple",
    "portrait": "framed-picture",
    "innocent": "baby",
    "substitute": "shuffle",
    "supplement": "plus",
    "filter": "hourglass",
    "flexible": "pretzel",
    "abstract": "palette",
    "distant": "milky-way",
    "shade": "umbrella",
    "grain": "rice-plant",
    "situate": "pushpin",
    "summarize": "clipboard",
    "leap": "kangaroo",
    "snap": "camera",
    "probability": "game-die",
    "uncertainty": "question-red",
    "swear": "cursing",
    "refugee": "running",
    "shore": "beach",
    "comprise": "puzzle-piece",
    "stir": "cooking",
    "excitement": "party",
    "pregnancy": "pregnant",
    "experimental": "test-tube",
    "institutional": "classical-building",
    "slice": "pizza",
    "wander": "footprints",
    "empire": "crown",
    "gentle": "dove",
    "attendance": "ticket",
    "ownership": "key",
    "qualification": "graduation-cap",
    "suspend": "pause",
    "functional": "gear",
    "voluntary": "raise-hands",
    "pale": "white",
    "stain": "droplet",
    "athlete": "running",
    "server": "laptop",
    "structural": "brick",
    "fool": "joker",
    "alongside": "holding-hands",
    "unite": "handshake",
    "wipe": "paper-roll",
    "weird": "alien",
    "fade": "crescent-moon",
    "cough": "sneeze",
    "hypothesis": "crystal-ball",
    "theoretical": "thought",
    "curtain": "theater",
    "mayor": "classical-building",
    "darkness": "crescent-moon",
    "aunt": "woman",
    "tournament": "trophy",
    "registration": "clipboard",
    "fragment": "puzzle-piece",
    "listener": "ear",
    "tender": "heart",
    "density": "brick",
    "ugly": "ogre",
    "module": "brick",
    "autumn": "maple-leaf",
    "cheek": "kiss",
    "attachment": "paperclip",
    "holder": "raise-hands",
    "solar": "sun",
    "noun": "letters",
    "fortunate": "four-leaf-clover",
    "hunger": "cutlery",
    "insure": "shield",
    "ashamed": "blush",
    "found": "magnify",
    "thirst": "soda",
}

# Gap → tip lemma (redundant). Tips should preferably be covered or kept as metaphors.
# Adverbs and near-duplicates collapse here; keep stems for metaphor attach when possible.
REDUNDANT: dict[str, str] = {
    "especially": "particular",
    "particularly": "particular",
    "specifically": "specific",
    "clearly": "clear",
    "obviously": "obvious",
    "normally": "normal",
    "basically": "basic",
    "mainly": "main",
    "fairly": "fair",
    "necessarily": "necessary",
    "slowly": "slow",
    "strongly": "strong",
    "entirely": "entire",
    "significantly": "significant",
    "surely": "sure",
    "frequently": "frequent",
    "properly": "proper",
    "closely": "close",
    "widely": "wide",
    "equally": "equal",
    "merely": "mere",
    "truly": "true",
    "effectively": "effective",
    "perfectly": "perfect",
    "personally": "personal",
    "originally": "original",
    "primarily": "primary",
    "rapidly": "rapid",
    "deeply": "deep",
    "typically": "typical",
    "respectively": "typical",
    "ultimately": "end",
    "virtually": "almost",
    "heavily": "heavy",
    "regularly": "regular",
    "briefly": "brief",
    "similarly": "similar",
    "newly": "new",
    "occasionally": "rare",
    "precisely": "precise",
    "successfully": "successful",
    "roughly": "rough",
    "literally": "true",
    "automatically": "gear",
    "dramatically": "dramatic",
    "consequently": "result",
    "potentially": "possible",
    "hopefully": "hope",
    "surprisingly": "surprise",
    "differently": "different",
    "firstly": "first",
    "secondly": "second",
    "quietly": "quiet",
    "reasonably": "reason",
    "subsequently": "subsequent",
    "gently": "gentle",
    "faithfully": "true",
    "firmly": "hard",
    "greatly": "great",
    "partly": "part",
    "altogether": "total",
    "monthly": "month",
    "weekly": "week",
    "barely": "almost",
    "presumably": "guess",
    "regardless": "ignore",
    "whilst": "while",
    "investment": "invest",
    "investor": "invest",
    "application": "apply",
    "assessment": "assess",
    "requirement": "need",
    "recommendation": "suggest",
    "participant": "participate",
    "participation": "participate",
    "leadership": "leader",
    "commitment": "promise",
    "protection": "protect",
    "judgment": "judge",
    "selection": "choose",
    "presentation": "show",
    "reduction": "reduce",
    "complaint": "complain",
    "impression": "impress",
    "friendly": "friend",
    "lovely": "love",
    "dangerous": "danger",
    "industrial": "industry",
    "electronic": "computer",
    "criminal": "crime",
    "scientific": "science",
    "academic": "school",
    "emotional": "emotion",
    "educational": "school",
    "presidential": "president",
    "competitive": "compete",
    "democratic": "democracy",
    "agricultural": "farm",
    "biological": "life",
    "psychological": "mind",
    "experimental": "test",
    "institutional": "institution",
    "structural": "structure",
    "functional": "work",
    "theoretical": "theory",
    "conventional": "custom",
    "controversial": "debate",
    "continuous": "continue",
    "comprehensive": "complete",
    "commercial": "sale",
    "historic": "history",
    "literary": "literature",
    "visual": "see",
    "clinical": "medical",
    "ethnic": "culture",
    "racial": "race",
    "digital": "computer",
    "universal": "world",
    "absolute": "total",
    "acceptable": "ok",
    "adequate": "enough",
    "attractive": "beautiful",
    "capable": "can",
    "consistent": "same",
    "contemporary": "now",
    "dependent": "need",
    "efficient": "fast",
    "equivalent": "equal",
    "extensive": "large",
    "flexible": "soft",
    "fortunate": "luck",
    "fundamental": "basic",
    "helpful": "help",
    "illegal": "law",
    "immediate": "now",
    "impressive": "great",
    "innocent": "pure",
    "intense": "strong",
    "internal": "inside",
    "massive": "huge",
    "mutual": "share",
    "ordinary": "normal",
    "permanent": "always",
    "pleasant": "nice",
    "precise": "exact",
    "relevant": "important",
    "reliable": "trust",
    "severe": "bad",
    "significant": "important",
    "similar": "same",
    "slight": "little",
    "solid": "hard",
    "stable": "steady",
    "strict": "hard",
    "substantial": "large",
    "sufficient": "enough",
    "suitable": "fit",
    "temporary": "moment",
    "unable": "can",
    "unlikely": "doubt",
    "unusual": "rare",
    "valuable": "value",
    "violent": "violence",
    "visible": "see",
    "vital": "important",
    "voluntary": "free",
    "wealthy": "money",
    "wise": "smart",
}


def parse_meta(cell: str) -> list[str]:
    return [p.strip().lower() for p in (cell or "").split(";") if p.strip()]


def load_lemma_map_rows() -> list[tuple[str, str, str]]:
    rows: list[tuple[str, str, str]] = []
    for line in LEMMA_MAP.read_text(encoding="utf-8").splitlines():
        t = line.strip()
        if not t or t.startswith("#") or t.startswith("surface,"):
            continue
        parts = next(csv.reader([t]))
        if len(parts) < 2:
            continue
        surface, lemma = parts[0].strip().lower(), parts[1].strip().lower()
        kind = (
            parts[2].strip().lower()
            if len(parts) > 2 and parts[2].strip()
            else "inflection"
        )
        if surface and lemma and surface != lemma:
            rows.append((surface, lemma, kind))
    return rows


def is_flaggish(literal: str, emoji: str) -> bool:
    if any(0x1F1E6 <= ord(c) <= 0x1F1FF for c in emoji):
        return True
    lit = literal.lower()
    return any(
        x in lit
        for x in (
            "islands",
            "republic",
            "territor",
            "federation",
            "georgia-south",
            "bosnia",
        )
    )


def soft_match(
    lemma: str,
    empty_lits: set[str],
    token_index: dict[str, list[str]],
) -> str | None:
    if lemma in PREFER and PREFER[lemma] in empty_lits:
        return PREFER[lemma]
    # exact literal token
    hits = [l for l in token_index.get(lemma, []) if l in empty_lits]
    if len(hits) == 1:
        return hits[0]
    if hits:
        # prefer shorter / exacter
        hits.sort(key=lambda l: (0 if l == lemma else 1, len(l), l))
        return hits[0]
    # substring containment
    cands = [l for l in empty_lits if lemma in l.split("-") or lemma in l]
    if cands:
        cands.sort(key=len)
        return cands[0]
    return None


def main() -> None:
    pub = list(csv.DictReader(PUBLISHED.open(encoding="utf-8")))
    by_lit = {r["literal"].strip().lower(): r for r in pub}
    literals = set(by_lit)

    # Validate prefer targets
    bad_prefer = {k: v for k, v in PREFER.items() if v not in by_lit}
    if bad_prefer:
        print(f"WARN: {len(bad_prefer)} PREFER targets missing; will soft/auto instead")
        for k, v in list(bad_prefer.items())[:15]:
            print(f"  {k}→{v}")

    gaps = [
        r["lemma"].strip().lower()
        for r in csv.DictReader(COVERAGE.open(encoding="utf-8"))
        if r["status"] == "gap"
    ]
    gap_set = set(gaps)

    covered = {
        r["lemma"].strip().lower()
        for r in csv.DictReader(COVERAGE.open(encoding="utf-8"))
        if r["status"] in ("literal", "metaphor")
    }

    existing_map = load_lemma_map_rows()
    existing_surfaces = {s for s, _, _ in existing_map}

    lit_claimed: dict[str, str] = {}
    lemma_home: dict[str, str] = {}
    for r in pub:
        lit = r["literal"].strip().lower()
        parts = parse_meta(r["metaphorical"])
        if parts:
            lit_claimed[lit] = parts[0]
            lemma_home[parts[0]] = lit

    # 1) Redundant collapses first (don't attach those)
    new_redundant: list[tuple[str, str]] = []
    for surface, tip in REDUNDANT.items():
        if surface not in gap_set:
            continue
        if surface in existing_surfaces:
            gap_set.discard(surface)
            continue
        if tip == surface:
            continue
        new_redundant.append((surface, tip))
        gap_set.discard(surface)

    remaining = [g for g in gaps if g in gap_set]

    empty_rows = [
        (r["emoji"], r["literal"].strip().lower())
        for r in pub
        if r["literal"].strip().lower() not in lit_claimed
    ]
    empty_lits = {lit for _, lit in empty_rows}

    token_index: dict[str, list[str]] = defaultdict(list)
    blacklist = {
        "see-no-evil",
        "hear-no-evil",
        "speak-no-evil",
        "love-hotel",
        "hot-dog",
        "milky-way",
        "statue-of-liberty",
        "isle-of-man",
        "call-me",
        "rock-on",
        "mind-blown",
    }
    for lit in empty_lits:
        if lit in blacklist:
            continue
        for tok in lit.split("-"):
            if len(tok) >= 3:
                token_index[tok].append(lit)

    # 2) Soft / prefer attach
    soft_n = 0
    for lemma in list(remaining):
        if lemma in lemma_home or lemma in literals:
            gap_set.discard(lemma)
            continue
        lit = soft_match(lemma, empty_lits, token_index)
        if lit is None:
            continue
        lit_claimed[lit] = lemma
        lemma_home[lemma] = lit
        empty_lits.discard(lit)
        gap_set.discard(lemma)
        soft_n += 1

    remaining = [g for g in gaps if g in gap_set]

    # 3) Auto-fill onto remaining empties (non-flag first)
    empty_sorted = sorted(
        [(e, lit) for e, lit in empty_rows if lit in empty_lits],
        key=lambda x: (is_flaggish(x[1], x[0]), x[1]),
    )
    auto_n = 0
    for lemma, (_e, lit) in zip(remaining, empty_sorted):
        if lemma in literals or lemma in lemma_home:
            continue
        lit_claimed[lit] = lemma
        lemma_home[lemma] = lit
        empty_lits.discard(lit)
        gap_set.discard(lemma)
        auto_n += 1

    leftover = [g for g in gaps if g in gap_set]

    # 4) Overflow → stretch redundant to covered tip
    fallback = "idea" if "idea" in covered else "make"
    for lemma in leftover:
        if lemma in existing_surfaces:
            continue
        tip = fallback
        for c in sorted(covered):
            if len(c) >= 4 and c[:4] == lemma[:4] and c != lemma:
                tip = c
                break
        new_redundant.append((lemma, tip))
        gap_set.discard(lemma)

    # Write lemma map
    comments = [
        "# Inflected / alternate surface → core lemma for NGSL coverage.",
        "# Columns: surface,lemma,kind  (kind = inflection | redundant; default inflection).",
        "# Inflection → status skip-inflection; synonym/near-duplicate → status redundant.",
        "# One row per surface. Identity mappings omitted.",
        "# Coverage emits mapped-away surfaces separately; content status is on the resolved lemma.",
        "# Redundant rows may map one NGSL lemma onto another (e.g. cash → money).",
        "# Do not map a surface that is its own distinct NGSL lemma when collapsing would be wrong (e.g. found, left).",
    ]
    merged: dict[str, tuple[str, str]] = {}
    for s, l, k in existing_map:
        merged[s] = (l, k)
    for s, l in new_redundant:
        if s not in merged:
            merged[s] = (l, "redundant")

    with LEMMA_MAP.open("w", encoding="utf-8", newline="") as f:
        for c in comments:
            f.write(c + "\n")
        f.write("surface,lemma,kind\n")
        for s in sorted(merged):
            l, k = merged[s]
            f.write(f"{s},{l},{k}\n")

    # Update published
    for r in pub:
        lit = r["literal"].strip().lower()
        r["metaphorical"] = lit_claimed.get(lit, "")

    with PUBLISHED.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(
            f,
            fieldnames=["emoji", "literal", "clarity", "metaphorical"],
            lineterminator="\n",
        )
        w.writeheader()
        w.writerows(pub)

    # Rebuild metaphor-extra
    extras: list[tuple[str, str]] = []
    seen: set[str] = set()
    for r in pub:
        lit = r["literal"].strip().lower()
        parts = parse_meta(r["metaphorical"])
        if len(parts) == 1 and parts[0] not in seen:
            extras.append((parts[0], lit))
            seen.add(parts[0])

    with EXTRA.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=["lemma", "literal"], lineterminator="\n")
        w.writeheader()
        for lemma, lit in sorted(extras):
            w.writerow({"lemma": lemma, "literal": lit})

    multi = sum(1 for r in pub if len(parse_meta(r["metaphorical"])) > 1)
    print(f"New redundant: {len(new_redundant)}")
    print(f"Soft/prefer metaphors: {soft_n}")
    print(f"Auto-fill metaphors: {auto_n}")
    print(f"Overflow forced redundant: {len(leftover)}")
    print(f"Metaphor-extra rows: {len(extras)}")
    print(f"Published with metaphorical: {sum(1 for r in pub if r['metaphorical'])}")
    print(f"Multi-metaphor rows: {multi}")
    print(f"Empty slots left: {len(empty_lits)}")


if __name__ == "__main__":
    main()
